In [6]:
## Welcome to Numpy

In [1]:
import numpy as np


In [15]:
myarr = np.array([[3,6,8]],np.int32)
# here np.int32 is the size
print(myarr[0][1])
print(myarr[0])
myarr.shape # it will return shape of the array


6
[3 6 8]


(1, 3)

In [16]:
# changing the value
myarr[0,1] = 28
print(myarr)

[[ 3 28  8]]


In [20]:
#creating array of zero'se
zeros = np.zeros([3,4])
print(zeros)
print(f'Shape pf the array : {zeros.shape}')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape pf the array : (3, 4)


In [21]:
# arange 
rng = np.arange(15)
print(f'my array : {rng}')

my array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
#equal space in list using the array
#linspace
eqspace = np.linspace(1,50,10)
eqspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
# empty
emp = np.empty((4,6))
emp


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
# like 
en = np.empty_like(eqspace)
en

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
# reshape
re = rng.reshape(3,5)
re

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
# numpy Axis
# 1D -> [1,2,3,4,5] -> 1 [Axis 0]
# 2D -> [[1,2,3,4,5][6,7,8,9,10]] -> 2 [Axis 0,Axis 1]

In [35]:
a1 = re.sum(axis= 0)
a1 # here axis 0 represent column 


array([15, 18, 21, 24, 27])

In [36]:
a2 = re.sum(axis = 1)
a2 # here axis = 1 means rows

array([10, 35, 60])

In [37]:
# for transpos it means coverting rows into column
re.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [38]:
# for dimentions
re.ndim

2

In [48]:
# for checking max element
print(re.argmax())
# it will return index of the element
re.argsort()

14


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [51]:
# for search 
np.where(re>9)

(array([2, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))

In [54]:
np.where(a1>24)
# it return index of the element

(array([4], dtype=int64),)